# Introduction à Python
Ceci est un jupyter-notebook, il permet de mélanger du code et du texte dans un même document. Le document est divisé en cellules qui peuvent être modifiées en les sélectionnant par un double clique ou avec **Entrée**. Elles peuvent ensuite être executées avec **Ctrl+Entrée**.

Vous devrez compléter du code aux endroits indiqués. Le plus souvent un problème sera divisé en 3 cellules : une cellule d'énoncé (du texte), une cellule à remplir et une cellule de test. N'oubliez pas d'exécuter votre cellule à remplir même si elle ne fait rien en soi. Attention au cas où votre code est répartie sur plusieurs cellules, l'ordre dans lequelle vous les executez est important.

Cette introduction est destinée à des personnes sachant déjà programmer dans un autre language et se concentre surtout sur les spécificités de Python. Vous devrez chercher par vous même la syntaxe de Python pour les éléments de programmations "classiques" qui ne sont pas détaillés dans ce _notebook_.

Python se caractérise aussi par de nombreuses méthodes ajoutées de base aux différents objets du langage. Si vous cherchez à faire quelque chose de standard, ça a sûrement déjà été implémenté ! **Aidez-vous d'internet et des moteurs de recherche !**

## 0. Le "Zen de Python"
Le "Zen de Python" résume en 19 aphorismes la phylosophie de Python. Un _easter egg_ dans l'interpreteur de Python permet de l'afficher avec :
```python
import this
```
Exécuter la cellule suivante pour afficher le "Zen de Python".

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


## 1. L'indentation en Python
Le Python se démarque de la plupart des autres language par le fait que son code s'exécute en fonction de son indentation. Par exemple les codes : 
```python
a = 0
i = 0
for i in range(10):
    print(i)
    a += i
```
et
```python
a = 0
i = 0
for i in range(10):
    print(i)
a += i
```

ne font pas la même chose ! En Python, les blocs de code n'ont pas de begin ou end explicites, le seul délimiteur est les deux points (":") et l'indentation du code lui-même.

## 2. Nombres entiers et flottants
__int__ désigne un entier,
__float__ désigne un nombre flottant. En python 3, "/" est l'opérateur de division, "//" est l'opérateur de division entière et "%" le modulo.

Exercice : remplir le code pour faire une division euclidienne des nombres a et b en complétant la définition de la fonction. Noter qu'il est possible de renvoyer plusieurs valeurs après un __return__. 

In [5]:
def division_reelle(a, b):
    quotient = a//b
    reste = a%b
    return quotient, reste

In [6]:
## Cellule de test de votre code : à ne pas modifier.
# Renvoie "Bonne réponse" ou "Erreur" si le code s'exécute mais que les résultats sont faux.

# Affichage des résultats : 
print(division_reelle(5,5))
print(division_reelle(5,2))
print(division_reelle(1,5))    

# Validation du code :
try:
    assert(division_reelle(5,5) == (1, 0))
    assert(division_reelle(5,2) == (2, 1))
    assert(division_reelle(1,5) == (0, 1))    
    print('Bonne réponse !')

except AssertionError: 
    print('Erreur !')

(1, 0)
(2, 1)
(0, 1)
Bonne réponse !


## 3. Chaînes de caractères

En Python, le type chaine de caractères se note par __str__. C'est une classe qui possède ses méthodes propres. __Référez-vous à la documentation.__

Exercices: 
1. Compléter la fonction "separe(a, b)" qui sépare la chaine de caractères _a_ à chaque occurence de _b_.
2. Compléter la fonction "joindre(a, b)" qui rejoint la liste de chaine de caractères _a_ avec la chaîne de caractères _b_.

In [9]:
'bonjour ' + 'mon ami'

'bonjour mon ami'

In [17]:
def separe(a, b):
        
    chaine_separee = a.split(b);
    return chaine_separee

def joindre(a, b):
    chaine_jointe = b.join(a)
    return chaine_jointe

In [18]:
## Cellule de test de votre code : à ne pas modifier.
# Renvoie "Bonne réponse" ou "Erreur" si le code s'exécute mais que les résultats sont faux.

# Affichage des résultats : 
print(separe('awsdww2e2dsd','2'))
print(separe('un deux trois',' '))
print(joindre(['un', 'deux', 'trois'],'-'))
print(joindre(['j\'aime', 'les', 'sandwichs'],' '))
      
# Validation du code :
try:
    assert(separe('awsdww2e2dsd','2')==['awsdww','e','dsd'])
    assert(separe('un deux trois',' ')==['un', 'deux', 'trois'])
    assert(joindre(['un', 'deux', 'trois'],'-')== 'un-deux-trois')
    assert(joindre(['j\'aime', 'les', 'sandwichs'],' ')=='j\'aime les sandwichs')
    print('Bonne réponse !')

except AssertionError: 
    print('Erreur !')

['awsdww', 'e', 'dsd']
['un', 'deux', 'trois']
un-deux-trois
j'aime les sandwichs
Bonne réponse !


## 4. Listes

La liste est l'un des éléments centraux de la programmation en Python. Elle peut contenir des objets de n'importe quelle classe. On peut aussi regrouper dans une même liste des objets de classes différentes. Elle est définie par des crochets "[ ]".

Les fonctions __append__ et __remove__ permettent respectivement d'ajouter et de retirer des éléments à une liste. 
On peut parcourir les élements d'une liste avec une boucle __for__:

```python
ma_liste = [1, 2, 3, 45]
for i in ma_liste:
    print(i)
    
# Résultat
>>> 1
    2
    3
    45
```

Exercices: 
1. Compléter la fonction separe_type(a), qui renvoie deux listes en séparant les élements de _a_. 
    Dans la première liste on regroupe les nombres de _a_, dans la deuxième liste on regroupe les chaînes de charactères de _a_. Si un élément n'est ni un nombre ni une chaine de charactères, il est ignoré.
2. Renvoyer la liste de nombres triée.

In [47]:
def separe_type(a):
    
    nombres = []
    chaines_de_caracteres = []
    
    for element in a:
        if type(element) == int:
            nombres.append(element)
        if type(element) == str:
            chaines_de_caracteres.append(element)
        nombres.sort()
    
    
    ## À compléter.
    return nombres, chaines_de_caracteres
    

In [48]:
## Cellule de test de votre code : à ne pas modifier.
# Renvoie "Bonne réponse" ou "Erreur" si le code s'exécute mais que les résultats sont faux.

# Affichage des résultats : 
print(separe_type([1, 2, 3, '2', 'sdasd', 'ws']))
print(separe_type(['un deux trois', ' ', 2]))
print(separe_type(['un', 'deux', 'trois']))
print(separe_type([2, 3, 41, 2]))
      
# Validation du code :
try:
    assert(separe_type([1, 2, 3, '2', 'sdasd', 'ws']) == ([1, 2, 3],['2', 'sdasd', 'ws']))
    assert(separe_type(['un deux trois', ' ', 2]) == ([2],['un deux trois', ' ']))
    assert(separe_type(['un', 'deux', 'trois'])==([],['un', 'deux', 'trois']))
    assert(separe_type([2, 3, 41, 2]) == ([2, 2, 3, 41], []))
    print('Bonne réponse !')

except AssertionError: 
    print('Erreur !')

([1, 2, 3], ['2', 'sdasd', 'ws'])
([2], ['un deux trois', ' '])
([], ['un', 'deux', 'trois'])
([2, 2, 3, 41], [])
Bonne réponse !


In [53]:
range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [70]:
range(10)[-2]

8

La sélection des éléments d'une liste peut se faire avec un simple indice (exemple : ```liste[a]``` ), avec deux indices pour indiquer un interval (exemple : ```liste[a:b]```) ou avec trois indices pour indiquer un pas (exemple : ```liste[a:b:c]```). Un indice négatif permet de sélectionner des éléments en partant de la fin de la liste.

Exercices :
1. Créer une fonction ```select1``` qui retourne une nouvelle liste avec un élement sur trois sans les 5 premiers.
2. Créer une fonction ```select2``` qui retourne une nouvelle liste à l'envers et sans les trois derniers éléments de la liste original.

In [62]:
def select1(l):
    return l[5:len(l):3] # À compléter en une ligne

def select2(l):
    return l[-4::-1] # À compléter en une ligne

In [63]:
## Cellule de test de votre code : à ne pas modifier.
# Renvoie "Bonne réponse" ou "Erreur" si le code s'exécute mais que les résultats sont faux.

# Affichage des résultats : 
print(select1(list(range(20))))
print(select2(list(range(20))))

# Validation du code :
try:
    assert(select1(list(range(20)))==[5, 8, 11, 14, 17])
    assert(select2(list(range(20)))==[16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
    
    print('Bonne réponse !')

except AssertionError: 
    print('Erreur !')

[5, 8, 11, 14, 17]
[16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
Bonne réponse !


## 5. Dictionnaires

Les dictionnaires sont très pratiques et peuvent être considérés comme des listes avec des noms aux éléments. En revanche ils ne sont pas ordonnés contrairement aux listes.

On utilise "{a:b, c:d}" pour les définir. Ici, a et c sont les clés du dictionnaire et b et d les valeurs associées à ces clés. 

Exercice: 
    Définisser une fonction "dictionnaire" qui prend une liste de tuples de taille quelconque (ex: [(1,2), (3,5)]) et qui les met dans un dictionnaire avec le premier élément de chaque tuple comme clé et le deuxième élément comme valeur.

In [1]:
montuple = (1,2), (1,3)

montuple[0]

(1, 2)

In [10]:
def dictionnaire(l_tuple):
    
    resultat = {}
    
    for i in range(len(l_tuple)):
        
        ma_liste = l_tuple[i]
        
        for j in range(len(ma_liste)):
            resultat[ma_liste[0]] = ma_liste[1]
            
            
    
        
    return resultat

In [11]:
## Cellule de test de votre code : à ne pas modifier.
# Renvoie 'Bonne réponse' ou 'Erreur' si le code s'exécute mais que les résultats sont faux.

# Validation du code :
try:
    assert dictionnaire([(1,2), (3,5)]) == {1:2, 3:5}
    print('Bonne réponse !')

except AssertionError: 
    print('Erreur !')

Bonne réponse !


## 6. Fonctions
Les fonctions en Python sont des outils assez versatiles : il n'y a pas besoin de préciser les types des entrées et des sorties !
Une fonction se définit avec le mot clé **def**, et renvoie le résultat avec **return**.
Le passage en argument d'objets de type complexes (différents de __int__ et __float__) s'effectue par référence. 

Exemple:
```python
element_complexe = [1]
element_base = 1

def incremente_base(i):
    i+=1

def incremente_liste(i):
    i[0]+=1
    
incremente_base(element_base)
print(element_base)
# Résultat
>>> 1
    
incremente_liste(element_complexe)
print(element_complexe)
# Résultat
>>> [2] 
```

Exercices : 
1. Définir une fonction **carre(n)** qui renvoie le carré d'un nombre en entrée
2. Définir une fonction **puissance(n)** qui renvoie le premier argument à la puissance du deuxième. i.e : puissance(3,3)=27
3. Définir une fonction **addition(l, n)** qui renvoie une nouvelle liste contenant tout les éléments de l plus un nombre n. Attention, l ne doit pas être modifiée.

In [14]:
def carre(n):
    return n*n

def puissance(n, arg):
    return n**arg

def addition(l,n):
    
    liste =[]
    
    for i in range(len(l)):
        liste.append(l[i]+1)
        
    return liste






# Compléter.

In [15]:
## Cellule de test de votre code : à ne pas modifier.
# Renvoie 'Bonne réponse' ou 'Erreur' si le code s'exécute mais que les résultats sont faux.

# Affichage des résultats : 
print(carre(2))
print(carre(9))
print(puissance(3,2))
print(puissance(9,4))
a = list(range(10))
print('a', a)
n = 1
b = addition(a, n)
print('b', b)
print('a', a)
# Validation du code :
try:
    assert(carre(2) == 4)
    assert(carre(9) == 81)
    assert(puissance(3,2)== 9)
    assert(puissance(9,4) == 6561.0)
    a = list(range(10))
    n = 1
    assert(addition(a, n) == [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    assert(a == list(range(10)))
    print('Bonne réponse !')

except AssertionError: 
    print('Erreur !')

4
81
9
6561
a [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
b [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Bonne réponse !


2

## 7. Listes par compréhension

Les listes par compréhension vous permettent de faire du code rapide et efficace : on peut intégrer directement des boucles __for__, __while__ ou même des conditions comme __if__ dans la définition de la liste. 

Exemple avec la liste des carrés :
```python
result = []
for i in range(100):
    result.append(i*i)
```
est équivalent à : 
```python
result = [i*i for i in range(100)]
```
Les listes par compréhension permettent d'avoir un code plus compacte et plus rapide car elles évitent de copier inutilement les listes. 

Exercice : 
1. Définir d'abord une fonction premier(n) qui, avec des boucles __for__, renvoie la liste des nombres premiers jusqu'à n exclu puis refaite le même exercice avec une liste par compréhension. 
2. Créer la fonction `tri_indice(l)` qui renvoie la liste d'index d'élements triés, par exemple : `tri_indice([2,1,4,5])=[1,0,2,3]`.

new_list = [function(item) for item in list if condition(item)]
[x for b in a for x in b]


In [2]:
def premier(n):
    
    liste = []
    
    
    for nombre in range(2, n):
        b=True
        
        for j in range(2,nombre-1):
            if nombre%j==0:
                b=False;
        
        if b==True:
            liste.append(nombre)
            
    return liste
            


#[nombre if nombre%j!==0 for nombre in range(2, n) for j in range(2,nombre-1)]



## Par compréhension :
def premier_c(n):
    
    
    
    
    return ## À compléter

def tri_indice(l):
    return # À compléter en une ligne

NameError: name 'n' is not defined

In [12]:
def premier(n):
    
    liste = []
    
    
    for nombre in range(2, n):
        b=True
        
        for j in range(2,nombre-1):
            if nombre%j==0:
                b=False;
        
        if b==True:
            liste.append(nombre)
            
    return liste
            

## Par compréhension :
def premier_c(n):
    
    
    b=True
    liste = [nombre for nombre in range(2, n) for j in range(2,nombre-1) if nombre%j == 0 ]
    r = [x for x in range(2, n) if x not in liste]
    
    
    return r ## À compléter

def tri_indice(l):
    return # À compléter en une ligne

In [13]:
## Cellule de test de votre code : à ne pas modifier.
# Renvoie "Bonne réponse" ou "Erreur" si le code s'exécute mais que les résultats sont faux.

# Affichage des résultats : 
import time
print('premier(20) :', premier(20))
start_time = time.time()
premier(100)
print('premier(100) a mis %s secondes' % (time.time() - start_time))
print('premier_c(20) :', premier_c(20))
start_time = time.time()
premier_c(100)
print('premier_c(100) a mis %s secondes' % (time.time() - start_time))
print('tri_indice', tri_indice([1,5,2,4,3]))

# Validation du code :
try :
    assert premier(20) == [2, 3, 5, 7, 11, 13, 17, 19]
    assert premier(100) == [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97] 
    assert premier_c(20) == [2, 3, 5, 7, 11, 13, 17, 19]
    assert premier_c(100) == [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97] 
    assert tri_indice([1,5,2,4,3]) == [0, 2, 4, 3, 1]
    print('Bonne réponse !')
    
except AssertionError: 
    print('Erreur !')

('premier(20) :', [2, 3, 5, 7, 11, 13, 17, 19])
premier(100) a mis 0.000941038131714 secondes
('premier_c(20) :', [2, 3, 5, 7, 11, 13, 17, 19])
premier_c(100) a mis 0.00151300430298 secondes
('tri_indice', None)
Erreur !


Python 3 permet aussi de créer des dictionnaires par compréhension.

Exercice : Créer la fonction `dictionnaire_premier(n)` qui renvoie un dictionnaire avec comme clés les nombres de 2 à n et comme valeur pour chaque clés x la liste des nombre premiers jusqu'à x exclu (exemple : `dictionnaire_premier(n)={0:[], 1:[], 2:[], 3:[2], 4:[2, 3], 5:[2, 3], 6:[2, 3, 5]}`). Vous pouvez réutiliser la fonction `premier_c`.

In [ ]:
def dictionnaire_premier(n):
    return # À compléter en une ligne

In [ ]:
## Cellule de test de votre code : à ne pas modifier.
# Renvoie "Bonne réponse" ou "Erreur" si le code s'exécute mais que les résultats sont faux.

# Affichage des résultats : 
print(dictionnaire_premier(10))

# Validation du code :
try :
    assert dictionnaire_premier(10) == {0: [], 1: [], 2: [], 3: [2], 4: [2, 3], 5: [2, 3], 6: [2, 3, 5], 7: [2, 3, 5], 8: [2, 3, 5, 7], 9: [2, 3, 5, 7]} 
    print('Bonne réponse !')
    
except AssertionError: 
    print('Erreur !')

## 8. Classes

Python est un langage avec beaucoup de classes (exepté les types élémentaires il n'y a que des classes !).

Exercice : 
Implémenter une classe Voiture qui : 
- a un attribut "carburant" intialisé à 50 (entier de max 100)
- a deux méthodes : 
    - avance(x) : consomme x de carburant, renvoie "J'ai avancé de `x`km", si x > carburant elle consomme tout le carburant et renvoie "J'ai avancé de `carburant`km".
    - station() : remplit le carburant au max

In [175]:
class Voiture:
    def __init__(self):
        self.carburant=50
        
    def avance(self, x):
        if x>self.carburant:
            carburant_return = self.carburant
            self.carburant = 0
            return("J\'ai avancé de " + str(carburant_return) + "km")
            
            
        else:
            self.carburant = self.carburant - x
            return("J\'ai avancé de " + str(x) + "km")
        
    def station(self):
        self.carburant = 100
        return self.carburant
        

In [176]:
## Cellule de test de votre code : à ne pas modifier.
# Renvoie "Bonne réponse" ou "Erreur" si le code s'exécute mais que les résultats sont faux.

# Validation du code :
try:
    voit = Voiture()
    assert voit.carburant == 50
    assert voit.avance(20) == 'J\'ai avancé de 20km'
    assert voit.carburant == 30
    assert voit.avance(200) == 'J\'ai avancé de 30km'
    assert voit.carburant == 0
    voit.station()
    assert voit.carburant == 100
    print('Bonne réponse !')
    
except AssertionError: 
    print('Erreur !')

Bonne réponse !


## 9. Arguments de fonctions

En python, on peut fournir à une fonction :
 - une liste d'arguments dans un ordre
 - une liste d'arguments avec des mots clés (Exemple : `fonction(faire=True)`, le mot clé sera faire, et prend la valeur `True` par défaut).
 
En revanche, il n'est pas obligatoire de spécifier combien d'arguments on va fournir à la fonction ! Les mots clés `*args` et `**kwargs` définissent des arguments facultatifs.

Dans une fonction quelconque, si on ajoute à sa définition `*args` et `**kwargs` de la manière suivante : 

```python
def fonction(*args, **kwargs):
    ...
    ...
    return resultat
```

alors on peut récupérer les arguments positionnels (sans mots-clés) dans la fonction avec `args` sous forme de liste, et les arguments avec mots-clés avec `kwargs` sous forme de dictionnaire. On peut aussi combiner avec des arguments obligatoires : 

```python
def fonction(argument1, argument2, *args, **kwargs):
    arguments = args
    dictionnaire = kwargs
    ...
    return resultat
```


Exercice : 
Faire une fonction `add_mul` qui prend tout les arguments facultatifs et les somme si l'argument `operation=somme` et les multiplie si `operation=multiplication`. L'argument par défaut est `operation=somme`.

In [181]:
def add_mul(*args, operation='somme'):
    
    somme_finale = 0
    multiplication_finale = 1
    
    arguments = args
    if operation == 'somme':
        for element in arguments:
            somme_finale = somme_finale + element
        return somme_finale
    else:
        for element in arguments:
            multiplication_finale = multiplication_finale * element
        return multiplication_finale
   

In [182]:
## Cellule de test de votre code : à ne pas modifier.
# Renvoie "Bonne réponse" ou "Erreur" si le code s'exécute mais que les résultats sont faux.

# Affichage des résultats : 
print(add_mul(1,2,3))
print(add_mul(2, 2, 2, 2, operation = 'multiplication'))

# Validation du code :
try:
    assert add_mul(1,2,3) == 6
    assert add_mul(2, 2, 2, 2, operation = 'multiplication') == 2**4
    print('Bonne réponse !')
    
except AssertionError: 
    print('Erreur !')

6
16
Bonne réponse !


## 10. Numpy

Numpy est une bibliothèque Python très utilisée pour le calcul scientifique. Elle permet de manipuler des tableaux multidimensionnelles et implémente les opérations d'algèbre linéaire de manière parallélisées. 

### Importation de Numpy

Avant de pouvoir utiliser les classes et les fonctions de  numpy, il faut l'importer.

Exercice : Importer la bibiothèque numpy et lui attribuer l'alias `np` 

In [186]:
# À compléter
import numpy as np

In [187]:
## Cellule de test de votre code : à ne pas modifier.
# Renvoie "Bonne réponse" ou "Erreur" si le code s'exécute mais que les résultats sont faux.

# Validation du code:
try:
    assert np
    assert np.array([1])
    print("Bonne réponse !")

except AssertionError: 
    print("Erreur !")

Bonne réponse !


### Les tableaux multidimensionnelles

Numpy introduit les `array` (tableaux multidimensionnelles) qui peuvent être créés de différentes manières comme par exemple à partir d'une liste. 

Exemple d'une matrice 3X2 créée à partir d'une liste de liste :
```Python
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
```

Exercice : 
Créer un tableau 3D de dimensions 2X2X2 contenant les nombres entiers de 0 à 7 à partir d'une liste.

In [188]:
t = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

# À compléter

In [189]:
## Cellule de test de votre code : à ne pas modifier.
# Renvoie "Bonne réponse" ou "Erreur" si le code s'exécute mais que les résultats sont faux.

# Validation du code:
try:
    assert (t == np.arange(8).reshape(2,2,2)).all()
    print("Bonne réponse !")

except AssertionError: 
    print("Erreur !")

Bonne réponse !


Voici une liste non exhaustive de fonction numpy permettant de créer des `array`. Certaines prennent en paramètre un tuple avec les dimensions de l'`array` :
```Python
b = np.zeros((2,2))   # Créer un tableau de dimension 2X2 rempli de 0
c = np.ones((2,2))    # Créer un tableau de dimension 2X2 rempli de 1
d = np.full((2,2), 7)  # Créer un tableau de dimension 2X2 rempli de 7
e = np.random.random((2,2))  # Créer un tableau 2X2 rempli par un tirage dans une loi uniforme d'intervalle [0,1)
```
Exercice : Rechercher la fonction numpy permettant de créer la matrice identité de dimension 3X3.

In [190]:
t = np.eye(3)

In [191]:
## Cellule de test de votre code : à ne pas modifier.
# Renvoie "Bonne réponse" ou "Erreur" si le code s'exécute mais que les résultats sont faux.

# Validation du code:
try:
    assert (t == np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])).all()
    print("Bonne réponse !")

except AssertionError: 
    print("Erreur !")

Bonne réponse !


### Indexation des tableau

__Par indice__ : Comme pour les listes Python, les éléments des tableaux numpy peuvent être accédés par indice avec l'opérateur crochet. Pour une matrice 2D, le premier indice indique la ligne et le deuxième la colonne. Cet opérateur renvoie une copie.
```Python
a = np.arange(16).reshape(4,4)
print(a)
>>> [[ 0  1  2  3]
     [ 4  5  6  7]
     [ 8  9 10 11]
     [12 13 14 15]]
print(a[1])
>>> [4 5 6 7]
print(a[1,1])
>>> 5
```
__Par _slices___ : Vous pouvez aussi indexer les tableaux numpy par tranche (_slice_). Attention, une __slice__ n'est qu'une vue des données et non une copie. Si vous modifiez la _slice_, le tableau original sera aussi modifié.

```Python
a = np.arange(16).reshape(4,4)
b = a[:2, 1:3]
b[0, 0] = 100
print(a)
>>> [[  0 100   2   3]
     [  4   5   6   7]
     [  8   9  10  11]
     [ 12  13  14  15]]

```
__Par booléen__ : La dernière façon de récupérer les éléments d'un tableau est d'utiliser une liste d'indices booléens.
```Python
a = np.arange(6)
print(a)
>>> [0 1 2 3 4 5]
print(a[[False, False, False, True, False, True]])
>>> [3 5]
```
Exercice : Utiliser l'indexation par un booléen pour sélectionner les nombres pairs dans le tableau `tab`.

In [196]:
tab = np.arange(1000)
liste = [True if i%2==0 else False for i in range(0,1000)]
tab_pair = tab[liste]# À compléter

In [197]:
## Cellule de test de votre code : à ne pas modifier.
# Renvoie "Bonne réponse" ou "Erreur" si le code s'exécute mais que les résultats sont faux.

# Validation du code:
try:
    assert (tab_pair == np.arange(0, 1000, 2)).all()
    print("Bonne réponse !")

except AssertionError: 
    print("Erreur !")

Bonne réponse !


### Les opérateurs

Numpy permet de faire les opérations de matrice par élément de manière parralélisée. En voici quelques unes :

```Python
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)
>>> [[ 6.0  8.0]
     [10.0 12.0]]
     
print(x - y)
>>> [[-4.0 -4.0]
     [-4.0 -4.0]]
     
print(x * y)
>>> [[ 5.0 12.0]
     [21.0 32.0]]
     
print(x / y)
>>> [[ 0.2         0.33333333]
     [ 0.42857143  0.5       ]]

print(np.sqrt(x))
>>> [[ 1.          1.41421356]
     [ 1.73205081  2.        ]]

print(np.sum(x))  # Somme de tous les éléments
>>> 10

print(np.sum(x, axis=0))  # Somme des colonnes (axe 0)
>>> [4 6]

print(np.sum(x, axis=1))  # Somme des lignes ( axe 1)
>>> [3 7]
```
L'opérateur "@" correspond au produit matriciel, `.T` donne la transposé (exemple : `mat.T`).

### Le _broadcasting_
Le _broadcasting_ permet de réaliser des opérations arithmétiques entre des matrices de tailles différentes et de façon très rapide. Par exemple si on veut ajouter à chaque ligne de la matrice `mat` le vecteur `vec` on pourrait utiliser une boucle __for__, mais le code suivant est beaucoup plus rapide :
```Python
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x + v)
>>> [[ 2  2  4]
     [ 5  5  7]
     [ 8  8 10]
     [11 11 13]]
```

## 11. La pep8
La pep8 est le guide de style de Python. Elle donne toutes les conventions afin d'uniformiser tous les codes Python. Même si ces conventions ne sont pas très importantes pour un débutant, il vaut mieux les connaitres si l'on doit un jour publier du code. Le texte est disponible à cette [adresse](https://www.python.org/dev/peps/pep-0008/) et vous en trouverez des résumés en cherchant sur internet.

Exercice :
Corriger le code en suivant les conventions décrites dans la pep8.


In [200]:
import time, os
from numpy import *
def MergeSort(alist):
    if len(alist)>1:
        mid=round(len(alist)/2)
        LeftHalf=alist[:mid]
        RightHalf=alist[mid:]
        MergeSort(LeftHalf)
        MergeSort(RightHalf)
        i=j=k=0
        
        while i<len(LeftHalf) and j<len(RightHalf):
            
            if not LeftHalf[i]> RightHalf[j]: 
                alist[k]=LeftHalf[i];
                i=i+1
            elif True: 
                alist[k]=RightHalf[j];
                j=j+1
                
            k=k+1
            
            
        while i<len(LeftHalf): 
            alist[k]=LeftHalf[i]; 
            i=i+1; 
            k=k+1
            
            
        while j < len(RightHalf): alist[k]=RightHalf[j]; j=j+1; k=k+1

l=[44,47,5,65,33,45,2,7,70,11,77,58,16,38,35,46,4,8,62,40,72,60,74,36,15,52,51,68,1,78,41,31,57,61,37,19,53,39,26,9,75,43,67,55,34,32,49,0,25,20,69,59,48,3,18,23,21,17,56,6,54,13,10,71,22,27,64,29,42,30,12,76,79,73,63,28,66,24,50,14]
start_time = time.time()
print(sort(l))
print('%s secondes' % (time.time() - start_time))
start_time = time.time()
MergeSort(l)
print(l)
print('%s secondes' % (time.time() - start_time))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79]
0.0015854835510253906 secondes
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]
0.0006730556488037109 secondes


## 12. Le _profiler_ Python

Comme beaucoup de language, Python contient un profiler intégré qui permet d'analyser le comportement d'un programme en décrivant le nombre d'appels et le temps passé dans chaque fonction. On peut l'appeler dans le terminal avec la commande suivante :
```bash
python -m cProfile -s cumtime script_a_analyser.py
```
Exercice : Recopier le programme de la partie sur la pep8 dans un script ".py" puis donner la sortie du _profiler_.